import click
import yaml
import os
import sys
from validator import PolicyValidator

POLICY_FILE = os.path.join(os.path.dirname(__file__), '../policies/compliance_rules.yaml')

@click.group()
def cli():
    """BaFin Compliant Self-Service Platform Gateway"""
    pass

@cli.command()
@click.option('--file', '-f', required=True, help='Path to the product definition YAML file.')
def create_product(file):
    """Request a new data product."""
    click.echo(f"Processing request from: {file}")
    
    try:
        with open(file, 'r') as f:
            request = yaml.safe_load(f)
    except Exception as e:
        click.echo(f"Error reading file: {e}")
        sys.exit(1)

    validator = PolicyValidator(POLICY_FILE)
    is_valid, errors = validator.validate_request(request)

    if not is_valid:
        click.echo(click.style("COMPLIANCE CHECK FAILED!", fg="red", bold=True))
        for err in errors:
            click.echo(f" - {err}")
        sys.exit(1)
    else:
        click.echo(click.style("Compliance Check Passed.", fg="green"))
        click.echo("Generating Terraform configuration...")
        
        # Simulation of Terraform Generation
        generate_terraform(request)

def generate_terraform(request):
    """
    Simulates writing a terraform.tfvars file or running terraform apply.
    """
    product_name = request['name']
    env = request['environment']
    
    tf_content = f"""
    # Auto-generated by Platform Gateway
    product_name = "{product_name}"
    environment  = "{env}"
    kms_key_arn  = "arn:aws:kms:eu-central-1:123456789012:key/simulation-key"
    """
    
    output_file = f"terraform/product_{product_name}_{env}.auto.tfvars"
    # Ensure directory exists for simulation purposes (root terraform dir)
    if not os.path.exists('terraform'):
        os.makedirs('terraform')
        
    with open(output_file, 'w') as f:
        f.write(tf_content)
    
    click.echo(f"Terraform variables written to {output_file}")
    click.echo(click.style("Ready for Provisioning. (Simulation Complete)", fg="blue"))

if __name__ == '__main__':
    cli()
